"""Setup initial database schema

Revision ID: bba57459fecb
Revises: 70e3a127faa7
Create Date: 2024-12-07 08:52:24.219607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba57459fecb'
down_revision: Union[str, None] = '70e3a127faa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('articles', sa.Column('title', sa.String(), nullable=False))
    op.add_column('articles', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('articles', sa.Column('content_image', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('articles', sa.Column('thumbnail_image', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('public_status', sa.Enum('public', 'private', 'draft', 'limited', 'members_only', name='publicstatus'), nullable=False))
    op.add_column('articles', sa.Column('prefectures', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('create_user_id', sa.Integer(), nullable=False))
    op.add_column('articles', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('public_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('articles', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('articles', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('articles', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.drop_index('ix_articles_name', table_name='articles')
    op.create_index(op.f('ix_articles_public_status'), 'articles', ['public_status'], unique=False)
    op.create_foreign_key(None, 'articles', 'users', ['create_user_id'], ['id'])
    op.drop_column('articles', 'description')
    op.drop_column('articles', 'name')
    op.add_column('users', sa.Column('user_icon', sa.String(), nullable=True))
    op.add_column('users', sa.Column('introduction_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('firebase_user_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('prefectures', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_user_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['firebase_user_id'])
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=True)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'prefectures')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'firebase_user_id')
    op.drop_column('users', 'points')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'introduction_text')
    op.drop_column('users', 'user_icon')
    op.add_column('articles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_public_status'), table_name='articles')
    op.create_index('ix_articles_name', 'articles', ['name'], unique=False)
    op.drop_column('articles', 'deleted_at')
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    op.drop_column('articles', 'public_at')
    op.drop_column('articles', 'likes_count')
    op.drop_column('articles', 'create_user_id')
    op.drop_column('articles', 'prefectures')
    op.drop_column('articles', 'public_status')
    op.drop_column('articles', 'thumbnail_image')
    op.drop_column('articles', 'content_image')
    op.drop_column('articles', 'content')
    op.drop_column('articles', 'title')
    op.drop_column('articles', 'category')
    # ### end Alembic commands ###
